language: node_js
node_js:
  - '10'
cache: yarn
install: yarn
jobs:
  include:
    - stage: 'Tests'
      name: 'Unit Tests'
      script: yarn test
    - name: 'Static type check'
      script: yarn flow
    - name: 'Static type coverage'
      script: yarn flow-coverage
